### ISSUE TITLE
su: dch: command not found

### ISSUE THREAD

**Issue by jonnius** [ubports/crossbuilder#2]
I am trying to run crossbuilder in a VM with Ubuntu 16.04. Setting up crossbuilder was successful, but when I run `crossbuilder` I get
```
-su: dch: command not found
```
I tried to install **devscripts** inside the lxd container. But it seems I cannot access the internet from within the container. The internet is accessible from within the VM. So something in this "inception" does not seems to work correctly. Any idea, what I could do?

**Comment by mardy** [comment]
Hi @jonnius , if you want to run something as root in the container you should run:

    lxc exec <container-name> bash

In my case this gives me a shell with a working internet connection. However, I believe that this won't solve your issue, because `devscripts` is already installed by crossbuilder [here](https://github.com/ubports/crossbuilder/blob/master/crossbuilder#L248). But it could be that something failed while setting up crossbuilder. Can you please paste the full logs of the error? Also please check, whether `devscripts` is installed in the container.

**Comment by mardy** [comment]
@jonnius do you still have this issue? If not, do you remember what you did to solve it?

**Comment by jonnius** [comment]
I had this in a VM with 16.04. I did not resolve it, but just gave up that VM. Now I am using crossbuilder on my system with 18.04.

**Comment by jonnius** [comment]
Seems like @UniversalSuperBox has found [the solution](https://forums.ubports.com/topic/1516/howto-contributing-to-app-development-with-crossbuilder/44)

**Comment by jonnius** [comment]
Seems like @UniversalSuperBox has found [the solution](https://forums.ubports.com/topic/1516/howto-contributing-to-app-development-with-crossbuilder/44)

**Comment by UniversalSuperBox** [comment]
Can you run `crossbuilder setup-lxd` again?

**Comment by jonnius** [comment]
`crossbuilder setup-lxd` brought up the dialog to setup the bridge. I used default values and now crossbuilder works like a charm. Thanks for your help!
